### ISSUE TITLE
Cant Use s3scanner on Windows 10 (Reopen?)

### ISSUE THREAD

**Issue by Wh1teZz** [sa7mon/S3Scanner#101]
Firstly, I'm going to have to apologise as I'm a uni student who's not sure if it's me doing something wrong or not...

under s3utils.py in the time_limit function, signal is used for async. However, SIGALRM is a linux-only signal, and causes it to crash on windows with the exception:

`Traceback (most recent call last):
  File ".\s3scanner.py", line 95, in <module>
    s3.checkBucket(line, slog, flog, args.dump, args.list)
  File "*\S3Scanner\s3utils.py", line 122, in checkBucket
    size = getBucketSize(bucket)  # Try to get the size of the bucket
  File "*\S3Scanner\s3utils.py", line 222, in getBucketSize
    with time_limit(SIZE_CHECK_TIMEOUT):
  File "*\S3Scanner\s3utils.py", line 26, in time_limit
    signal.signal(signal.SIGALRM, signal_handler)
AttributeError: module 'signal' has no attribute 'SIGALRM'`

I'm sorry if this isn't actually an issue and I'm doing something wrong :(

**Comment by sa7mon** [comment]
Thanks for filing a bug report for this. This issue is something I have not yet encountered as I developed this tool on a *nix host. 

Version 2.0 is currently underway and should fix this issue. As a temporary workaround, I'd recommend running the tool either in Linux VM or via Docker.

**Comment by sa7mon** [comment]
Closing this due to 2.0.0 release. Feel free to open a new issue if you run into this problem again.
