### ISSUE TITLE
Aws config issue

### ISSUE THREAD

**Issue by the-war10ck** [sa7mon/S3Scanner#105]
Hi, 
Despite configuring the AWS credentials after running the tool it giving me below warning.

Warning: AWS credentials not configured. Open buckets will be shown as closed. Run: `aws configure` to fix this.

**Comment by sa7mon** [comment]
Hi there - the tool will verify that you have credentials properly setup in
the context of the aws cli tool. To verify you have set them correctly,
make sure you have a `~/.aws/credentials` file and that the file contains
both a `aws_access_key_id` and `aws_secret_access_key`

**Comment by the-war10ck** [comment]
I configured it by doing aws configure and setting up my keys there, but I can't find my aws credentials and aws config file, 
So I am reinstalling whole awscli into my system. If you want to correct me here please do it, thanks.
