### ISSUE TITLE
Getting "AWS credentials not configured" error.

### ISSUE THREAD

**Issue by jonbornstein** [sa7mon/S3Scanner#107]
Hi,

For some reason, the script is not detecting that I have my AWS credentials configured.  I've rerun `aws configure` a few times just to be sure, but everything looks fine.  They're located in the normal directory `~/.aws/`.

I'm running the script with python3 on Ubuntu 20.

Any ideas?

**Comment by sa7mon** [comment]
To verify you have your credentials set correctly, you can run `aws sts get-caller-identity`. This is what the script does under the hood. If your credentials are set, you'll get a response like this:

```json
{
    "UserId": "asdfasdf",
    "Account": "12341234",
    "Arn": "arn:aws:iam::asdfasdfasdf:user/asdfasdf"
}
```

You should have a `~/.aws/credentials` file that looks like this:
```
[default]
aws_access_key_id = AKIA.....
aws_secret_access_key = asdfasdfasdf
```

**Comment by sa7mon** [comment]
Closing this due to 2.0.0 release. Feel free to open a new issue if you run into this problem again.
