### ISSUE TITLE
 unrecognized arguments: --include-closed

### ISSUE THREAD

**Issue by DominikWeglarz** [sa7mon/S3Scanner#108]
after command from your examples :
python ./s3scanner.py --include-closed --out-file found.txt --dump names.txt

I get error - unrecognized arguments: --include-closed

![error_s3scaner](https://user-images.githubusercontent.com/71975425/104635943-e749db80-56a2-11eb-9dde-c5942e83bd2a.png)

**Comment by thehappydinoa** [comment]
Please see #106 as I think this arg has been deprecated.

**Comment by sa7mon** [comment]
Closing this due to 2.0.0 release. Feel free to open a new issue if you run into this problem again.
