### ISSUE TITLE
Printing all url?

### ISSUE THREAD

**Issue by blckraven** [sa7mon/S3Scanner#116]
Hi, i have a question to s3scanner. I have loaded file with URLs like https://aaa.google.com and when I run s3scanner scan --buckets-file google.txt I have this output:

https | bucket_exists | AuthUsers: [], AllUsers: []
https | bucket_exists | AuthUsers: [], AllUsers: []
https | bucket_exists | AuthUsers: [], AllUsers: []
...

How to change that HTTP to full url like https://aaa.google.com

**Comment by sa7mon** [comment]
To scan a list of GCS buckets, you'll want to use s3scanner like this:

`python3 -m S3Scanner --endpoint-url https://storage.googleapis.com scan --buckets-file bucket_names.txt`

where `bucket_names.txt` contains **only** bucket names like this:
```
bucket_1
bucket_2
```
