### ISSUE TITLE
Download failed: Key:

### ISSUE THREAD

**Issue by cgaudit** [sa7mon/S3Scanner#117]
Hi
I got Download failed: Key message when it tried to retrieve the key
This is the command I use:
python3 -m S3Scanner dump -d . -f ./mypublicbuckets.txt
Is there a missing argument or it what?

In addition, is there a way to scan for only sensitive files (scripts, configuration files, sensitive information etc.) instead of touching all the accessed files and check it one by one?

BR

**Comment by sa7mon** [comment]
Can you please post the full stacktrace of the error? Also, the name of the bucket it failed on. If you don’t want to post the bucket name publicly, you can email me privately. My email is listed on my website.

**Comment by cgaudit** [comment]
Hi Dan
I'm sorry but unfortunately I can't ..
If there is a debug option I can post it here.
Regarding my next question can you please provide an answer?

**Comment by cgaudit** [comment]
Additionally, is there a size limit for bucket extracting?

**Comment by sa7mon** [comment]
> If there is a debug option I can post it here.
> Just to let you know- I checked the output and even though it show the error I described it still download it.

There is not currently a debug option, but that is a good idea for a feature to add. I'm guessing what you encountered is a bucket with open permissions that contained an object with custom permissions set on it.

> Additionally, is there a size limit for bucket extracting?

No, the tool will keep downloading all files in the bucket until it no longer can (meaning your disk is full).

**Comment by cgaudit** [comment]
Thank's! 
I think you should also add the bucket path to the results then we will know to quickly get there and take care.
I would also like to know if there Is there an option to hunt for sensitive information by definition?

**Comment by sa7mon** [comment]
All of the options currently available are listed in the README. I didn't intend this tool to replace the analysis the user needs to do.
