### ISSUE TITLE
Copying the commands on readme page using copy option on page copies the prefixed $ as well

### ISSUE THREAD

**Issue by karanb192** [sa7mon/S3Scanner#120]
Eg - $ s3scanner --endpoint-url https://sfo2.digitaloceanspaces.com scan --bucket my-bucket

**Comment by sa7mon** [comment]
Yeah, unfortunately I can't control that - GitHub's automatic formatting adds the copy button to any code blocks. I'd prefer to keep the dollar sign to indicate it's a command line
