### ISSUE TITLE
Cannot instantiate Bucket - legacy URL buckets

### ISSUE THREAD

**Issue by ShurayukiHime** [sa7mon/S3Scanner#132]
https://github.com/sa7mon/S3Scanner/blob/6a6760338bfc7948ce445f032519ec20eaea34a1/S3Scanner/S3Bucket.py#L95

Hi, I am trying to use this scanner with URLs such as 
- `https://s3.amazonaws.com/bucketname`, OR
-  `https://s3.region.amazonaws.com/bucketname`

But in both cases the code says I have an invalid bucket name.
I know (see [docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingBucket.html)) that a bucket name can be as part of the domain, but then how can I inspect the above buckets? (see [legacy endpoints](https://stackoverflow.com/a/61051130/7052103))

Thanks.

**Comment by sa7mon** [comment]
The scanner will accept bucket names in the following formats:

* `mybucket`
* `bucket:region`
* `mybucket.s3.amazonaws.com`

I should probably add `https://mybucket.s3.amazonaws.com` as a format too. Basically for now you just need to strip off the `https://` prefix.

**Comment by ShurayukiHime** [comment]
Alright, that works for now.
It would be nice to have this feature as well.

Cheers!
