### ISSUE TITLE
Create Nix package

### ISSUE THREAD

**Issue by sa7mon** [sa7mon/S3Scanner#138]
Miniflux example: https://github.com/NixOS/nixpkgs/commit/4973ac5ada0bbcf855e9a6089bb4f67efe778484

**Comment by sa7mon** [comment]
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/misc/act/default.nix

**Comment by lavafroth** [comment]
I added s3scanner to my fork of nixpkgs. Let me know if this looks good before I make a PR. https://github.com/NixOS/nixpkgs/compare/master...lavafroth:nixpkgs:master

**Comment by sa7mon** [comment]
@lavafroth Thanks for taking charge of this! 

I left a comment on the commit - the package name is misspelled currently. When I tag a new release, is there an automated process to update the Nix package? Or does someone need to manually make a new PR for each version.

**Comment by lavafroth** [comment]
An automatic way probably exists but I haven't checked it out yet. I'll update the code once I figure out how to update the version automatically.

**Comment by lavafroth** [comment]
The [nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/278867) is merged! I think we can close this issue now.

**Comment by sa7mon** [comment]
Awesome! Thank you for contributing the PR. I'll close this issue after I've added installation docs to the readme
