### ISSUE TITLE
Not public bucket

### ISSUE THREAD

**Issue by xhendev** [sa7mon/S3Scanner#168]
Is there a way to scrape all files from an bucket even when it shows "AccessDenied"?

**Comment by sa7mon** [comment]
If the READ permission is not allowed, no there is no way to list a bucket's contents. The only case where you might get around this is if the bucket has READ denied for the `AllUsers` group but it is allowed for `AuthenticatedUsers`. In that case, you just need to have AWS credentials configured in `~/.aws/credentials`.
