### ISSUE TITLE
blackarch linux

### ISSUE THREAD

**Issue by dualfade** [sa7mon/S3Scanner#236]
Evening, 
I packaged up the latest go release for blackarch.org

blackarch/s3scanner 451.7e470a9-1 (5.3 MiB 21.0 MiB) [blackarch blackarch-scanner]
    A tool to find open S3 buckets in AWS or other cloud providers.

sudo pacman -S s3scanner

Awesome tool and thank you for all the work. My fav just got an upgrade !
Sincerely,

**Comment by sa7mon** [comment]
Thank you for packaging the tool for another distro! Do you know if there's a way to automate updating the package when we create a new release?

**Comment by dualfade** [comment]
You are very welcome ! So our build system is automated and normally runs every Saturday. Packages are auto updated. So there should be nothing to do. Much appreciated !!

**Comment by sa7mon** [comment]
Info added to the readme just now. Thanks again!
