### ISSUE TITLE
flag provided but not defined: -endpoint-url

### ISSUE THREAD

**Issue by Drjacky** [sa7mon/S3Scanner#255]
### Existing Issues

- [X] I've searched the [current issues](https://github.com/sa7mon/S3Scanner/issues)

### Command

s3scanner --endpoint-url https://s3.amazonaws.com/example.com/ scan --bucket exampleb

### Observed behavior (what happened?)

I installed this formula a while ago and it had the endpoint-url option but today, I deleted that version and installed 3.0.4 and now it doesn't have this option!

### Expected behaviour

endpoint-url option

### Debug output

N/A

### OS Info

macOS 14.1

### Additional info

I see you have suggested a command with the endpoint-url in issues. so, it was there, but not anymore.

**Comment by Drjacky** [comment]
Okay, the version 2.0.2 has this option

**Comment by sa7mon** [comment]
The latest version of s3scanner has been completely rewritten. I would encourage you to read the README. If you are using AWS as a storage provider, no endpoint or provider flag is needed.

 If you are scanning another storage provider, use the `-provider` flag. If s3scanner does not support the provider you’re scanning, use the `custom` provider along with a config file.
