### ISSUE TITLE
No list/write permissions marked

### ISSUE THREAD

**Issue by janmasarik** [sa7mon/S3Scanner#73]
👋 
It seems that calling `BucketAcl` on bucket to which ACL you don't have read access is restricted. No read access to ACL is the default so `s3scanner` won't mark the buckets as listable or writable.
 
```python
>>> s3.BucketAcl("rubyci").load()
...
ClientError: An error occurred (AccessDenied) when calling the GetBucketAcl operation: Access Denied
```
```bash
docker run s3scanner rubyci.s3.amazonaws.com
2019-03-17 15:35:55   Warning: AWS credentials not configured. Open buckets will be shown as closed. Run: `aws configure` to fix this.

2019-03-17 15:36:04       [found] : rubyci | Unknown Size - timeout | ACLs: unknown - no aws creds
```

With bash, you can see that bucket **is** in fact listable:
```bash
$ curl rubyci.s3.amazonaws.com
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Name>rubyci</Name>
...
```

**Comment by sa7mon** [comment]
Thanks for the report! s3scanner gets the ACLs of a bucket by using the AWS API so if you don't have AWS credentials configured, it won't be able to check. I agree that if a bucket is open and can be listed, we should show that ACL in the output.

Is there any reason you're not using AWS credentials with the tool?

**Comment by janmasarik** [comment]
I am, but it doesn’t show listable it even if I’m authenticated and the
bucket is not mine.

Call above from python console is authenticated.

**Comment by sa7mon** [comment]
Thanks for the info. This project is long overdue for cleanup and improvements, but I most likely won't have time for that until mid-May at the earliest.
