### ISSUE TITLE
Cant Use s3scanner on Windows 10

### ISSUE THREAD

**Issue by dzhenway** [sa7mon/S3Scanner#76]
s3scanner.py -h
Traceback (most recent call last):
  File "C:\Python3\S3Scanner-master\s3scanner.py", line 12, in <module>
    import s3utils as s3
  File "C:\Python3\S3Scanner-master\s3utils.py", line 1, in <module>
    import sh
  File "C:\Python3\lib\site-packages\sh.py", line 36, in <module>
    support." % __version__)
ImportError: sh 1.12.14 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

#########################################################

pip3 install sh
Requirement already satisfied: sh in c:\python3\lib\site-packages (1.12.14)

pip3 install pbs
Requirement already satisfied: pbs in c:\python3\lib\site-packages (0.110)

pip3 install s3utils
Requirement already satisfied: s3utils in c:\python3\lib\site-packages (0.6.1)
Requirement already satisfied: boto>=2.39.0 in c:\python3\lib\site-packages (from s3utils) (2.49.0)

**Comment by sa7mon** [comment]
Thanks for reporting this. This project needs some work and I'll prioritize this issue. Until I get a fix tested and pushed, I'd suggest just using the tool in a VM or Windows Subsystem for Linux

**Comment by sa7mon** [comment]
Update: I'm currently working on resolving this. I've decided the best option is to remove `sh` as a dependency and just use Boto itself. The work is probably 75% complete at this point.
