### ISSUE TITLE
Problem on VPS

### ISSUE THREAD

**Issue by d0xo** [sa7mon/S3Scanner#84]
Have been having issues lately that have not been seen before.

Traceback (most recent call last):
  File "s3scanner.py", line 95, in <module>
    s3.checkBucket(line, slog, flog, args.dump, args.list)
  File "/root/tools/S3Scanner/s3utils.py", line 122, in checkBucket
    size = getBucketSize(bucket)  # Try to get the size of the bucket
  File "/root/tools/S3Scanner/s3utils.py", line 224, in getBucketSize
    for item in page['Contents']:
KeyError: 'Contents'

Have not seen this before

**Comment by d0xo** [comment]
Threads option or multiscan and an ctrl+c to skip big buckets would be appreciated also

**Comment by sa7mon** [comment]
Closing this due to 2.0.0 release with multi-threading support. Feel free to open a new issue if you run into this problem again.
