### ISSUE TITLE
Contents key error

### ISSUE THREAD

**Issue by kaushik853** [sa7mon/S3Scanner#85]
Hi ,
when i run this script i get Keyerror
for item in page['Contents']:
KeyError: 'Contents' for getBucketSize function
Any clue why is this?

**Comment by sa7mon** [comment]
This is a known issue in `master` that will hopefully be resolved soon. For now, use the [latest tagged release](https://github.com/sa7mon/S3Scanner/releases/latest) instead of the `master` branch.

**Comment by kaushik853** [comment]
Thanks Dan, 
Is the enhancement branch is the latest one?

**Comment by sa7mon** [comment]
After you've cloned the git repo, simply run `git checkout tags/1.0.0` to checkout the latest tagged release which in this case is 1.0.0

**Comment by jeffjbowie** [comment]
Add the following to line 223 of S3Utils.py:
`if "Contents" in page.keys():`

**Comment by sa7mon** [comment]
Closing this due to 2.0.0 release. If you run into this problem again, feel free to open a new issue.
